apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # We advise you to build, push and use your own image, instead of using instructor's image.      
        image: isakovitch/backend:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend-service-port
      port: 8081
      targetPort: 8080
  type: LoadBalancer
---  
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-mon
  namespace: monitoring
  # Because prometheus entity has following scrapeConfigSelector config...
  # scrapeConfigSelector:
  #  matchLabels:
  #    release: prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend-service-port
    path: /metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default