{
 "title": "frontend and backend services",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Backend 4XX 5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"(4|5)0(0|1|2|3|4)\", job=\"backend-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime backend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg by(namespace) (avg_over_time(up{namespace=\"default\", pod=~\"backend-app-.*\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend 4XX 5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"(4|5)0(0|1|2|3|4)\", job=\"frontend-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime frontend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg by(namespace) (avg_over_time(up{namespace=\"default\", pod=~\"frontend-app-.*\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}