{
 "title": "KPI Dashboards",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "KPI Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\", job=\"backend-service\"}[30s]) / rate(flask_http_request_duration_seconds_count{status=\"200\", job=\"backend-service\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "KPI Uptime: green when >= 99.95%",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg by(namespace) (avg_over_time(up{namespace=\"default\", pod=~\"backend-app-.*\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KPI Percentage of 4XX and 5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum(flask_http_request_total{status=~\"(4|5)0(0|1|2|3|4)\", job=\"backend-service\"}) / sum(flask_http_request_total{job=\"backend-service\"})",
     "legendFormat": "Percentage of 4XX and 5XX Errors over the total amount of requests"
    }
   ]
  },
  {
   "title": "4XX 5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"(4|5)0(0|1|2|3|4)\", job=\"backend-service\"})",
     "legendFormat": "4XX and 5XX errors"
    }
   ]
  },
  {
   "title": "Successfull requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{job=\"backend-service\", status=\"200\"})",
     "legendFormat": "Successfull Requests"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}